

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int PRUcode[] =  {
     0x00000000,
     0x00000000,
     0x00000000,
     0x00000000,
     0x00000000,
     0x00000000,
     0x00000000,
     0x00000000,
     0x24ffffc1,
     0x24ffff81,
     0x24ffffc2,
     0x24ffff82,
     0x2444e0c2,
     0x24719082,
     0xe1002281,
     0x2444e0c1,
     0x24d06481,
     0x09030202,
     0x0002e1e1,
     0x11062222,
     0x10222202,
     0x09034242,
     0x11784242,
     0x10424222,
     0x10626242,
     0x0b016262,
     0x09074242,
     0x11076262,
     0x12622222,
     0x24000062,
     0x11060202,
     0x117f2222,
     0x11804242,
     0xe1002182 };

