

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int PRUcode[] =  {
     0x00000000,
     0x00000000,
     0x00000000,
     0x00000000,
     0x00000000,
     0x00000000,
     0x00000000,
     0x00000000,
     0x91042480,
     0x1d04e0e0,
     0x81042480,
     0x240120e0,
     0x240002c1,
     0x24202881,
     0xe1002180,
     0x240010c0,
     0x24000080,
     0x240002c1,
     0x24202c81,
     0xe1002180,
     0x240000e1,
     0x24002661,
     0x24481add,
     0x24c1949d,
     0xe1003d81,
     0x240000e3,
     0x2405f5c4,
     0x24e10084,
     0x0501e3e3,
     0x76e3e4ff,
     0x24481add,
     0x24c1909d,
     0xe1003d81,
     0x240000e3,
     0x2405f5c4,
     0x24e10084,
     0x0501e3e3,
     0x76e3e4ff,
     0x21001600 };

